
# version: "3.9"

services:
  db:
    container_name: ezd_api_postgres_db
    restart: unless-stopped
    # platform: linux/amd64
    # image: postgres:latest
    build:
      context: ./db
      dockerfile: ./Dockerfile.pg
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_DOCKER_PORT}
    volumes:
      - ./ezd_api_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

