
FROM node:22-alpine

ENV TZ="America/Denver"
ENV USER=node
ENV HOME=/home/$USER
ENV OUTPUT_DIR=/home/jcd-web-dist

RUN apk update && apk upgrade
RUN apk --no-cache add git bash

WORKDIR ${HOME}/app

COPY ./build-jcd-web.sh .
RUN chmod +x build-jcd-web.sh

ENTRYPOINT [ "/bin/bash" ]
